Repository alerque/libertinus, pull requests merged in 2020-10, with the labels that each got.

#356 feat(symbols): Add 𝄆 and 𝄇 (U+1D106–7)
  sources/LibertinusMono-Regular.sfd
  sources/LibertinusSans-Bold.sfd
  sources/LibertinusSans-Italic.sfd
  sources/LibertinusSans-Regular.sfd
  sources/LibertinusSerif-Bold.sfd
  sources/LibertinusSerif-BoldItalic.sfd
  sources/LibertinusSerif-Italic.sfd
  sources/LibertinusSerif-Regular.sfd
  sources/LibertinusSerif-Semibold.sfd
  sources/LibertinusSerif-SemiboldItalic.sfd
  sources/LibertinusSerifDisplay-Regular.sfd
Labels: enhancement

#365 Build and package WOFF2 webfonts
  .github/workflows/fontship.yml
  rules.mk
Labels: build

#391 Restore style name fields
  sources/LibertinusSerif-BoldItalic.sfd
  sources/LibertinusSerif-Semibold.sfd
  sources/LibertinusSerif-SemiboldItalic.sfd
Labels: bug, build

#383 Remove uni2098 and uni2099 from superscript kerning
  FONTLOG.txt
  sources/LibertinusMath-Regular.sfd
  sources/LibertinusSans-Bold.sfd
  sources/LibertinusSans-Italic.sfd
  sources/LibertinusSans-Regular.sfd
  sources/LibertinusSerif-Bold.sfd
  sources/LibertinusSerif-BoldItalic.sfd
  sources/LibertinusSerif-Italic.sfd
  sources/LibertinusSerif-Regular.sfd
  sources/LibertinusSerif-Semibold.sfd
  sources/LibertinusSerifDisplay-Regular.sfd
Labels: bug, script latin

#398 Add ‘uni0453.ital’ and enable support for Macedonian italics
  FONTLOG.txt
  sources/LibertinusSans-Italic.sfd
  sources/LibertinusSerif-BoldItalic.sfd
  sources/LibertinusSerif-Italic.sfd
  sources/LibertinusSerif-SemiboldItalic.sfd
  sources/features/gsub.fea
  sources/features/locl.fea
Labels: enhancement, script cyrillic
